version: "3.9"
services:
  vision:
    image: ghcr.io/ganidande905/vision:${TAG:-latest}
    container_name: vision
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true